import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header(){
  return (
    <header className="flex items-center justify-left p-4 bg-gray-800 text-white text-xl">
      <h1 className="text-2xl font-bold"><a href="/">Game Lister using next.js!</a></h1>
      <nav>
        <ul className="flex space-x-4">
          <li><a href="/games" className="hover:underline px-5">Game list</a></li>
          <li><a href="/about" className="hover:underline px-5">About</a></li>
          <li><a href="/contact" className="hover:underline px-5">Contact me!</a></li>
        </ul>
      </nav>
    </header>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
